-- =========================================================
-- V1: 초기 스키마 (User / Restaurant / Vote)
-- 출처: docs/03_data_model_and_tech.md 2장 데이터 모델
-- 원칙: 모든 시각은 UTC 저장, hard delete 금지(상태로만 관리)
-- 'user' 는 PostgreSQL 예약어이므로 테이블명은 복수형(users/restaurants/votes) 사용
-- users.current_vote_id 와 votes 는 순환 FK 이므로 votes 생성 후 ALTER 로 제약 추가
-- =========================================================

-- ---------- users ----------
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_id        BIGINT       NOT NULL UNIQUE,
    nickname        VARCHAR(50),
    profile_image   VARCHAR(500),
    created_at      TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    last_login_at   TIMESTAMP,
    current_vote_id BIGINT          -- 현재 유효 1표 빠른 조회용 (FK 는 votes 생성 후 추가)
);

-- ---------- restaurants ----------
CREATE TABLE restaurants (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_place_id   VARCHAR(50)  NOT NULL UNIQUE,   -- 중복 방지 핵심 (지점별 고유)
    name             VARCHAR(200) NOT NULL,
    address          VARCHAR(500),
    road_address     VARCHAR(500),
    latitude         DECIMAL(10, 7),
    longitude        DECIMAL(10, 7),
    kakao_category   VARCHAR(200),
    phone            VARCHAR(30),
    place_url        VARCHAR(500),                   -- 카카오맵 외부 링크
    status           VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    category         VARCHAR(50)  NOT NULL DEFAULT 'TONKATSU',  -- V2 확장 대비
    vote_count       INT          NOT NULL DEFAULT 0,            -- 비정규화 캐시
    relocated_to_id  BIGINT,                          -- 이전 시 새 가게 연결 (RELOCATED 전용)
    closed_at        TIMESTAMP,                       -- 폐업 시점 (CLOSED 전용)
    created_by       BIGINT,
    created_at       TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    updated_at       TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    CONSTRAINT ck_restaurants_status
        CHECK (status IN ('ACTIVE', 'CLOSED', 'RELOCATED', 'PENDING', 'REJECTED')),
    CONSTRAINT fk_restaurants_relocated_to
        FOREIGN KEY (relocated_to_id) REFERENCES restaurants (id),
    CONSTRAINT fk_restaurants_created_by
        FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_restaurants_status_vote_count ON restaurants (status, vote_count DESC); -- 서울 단일 랭킹 조회 핵심
CREATE INDEX idx_restaurants_lat_lng         ON restaurants (latitude, longitude);     -- 지도 핀 표시용
CREATE INDEX idx_restaurants_category        ON restaurants (category);

-- ---------- votes ----------
CREATE TABLE votes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT    NOT NULL,
    restaurant_id BIGINT    NOT NULL,
    voted_at      TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    is_current    BOOLEAN   NOT NULL DEFAULT TRUE,
    version       BIGINT    NOT NULL DEFAULT 0,   -- @Version 낙관적 락
    CONSTRAINT fk_votes_user       FOREIGN KEY (user_id)       REFERENCES users (id),
    CONSTRAINT fk_votes_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants (id)
);

-- 1인 1표 DB 레벨 보장: 유효표(is_current=true)는 사용자당 하나
CREATE UNIQUE INDEX ux_votes_user_current ON votes (user_id) WHERE is_current = TRUE;
CREATE INDEX idx_votes_user_voted_at       ON votes (user_id, voted_at DESC);
CREATE INDEX idx_votes_restaurant_current  ON votes (restaurant_id, is_current);

-- ---------- 순환 FK 마무리 ----------
ALTER TABLE users
    ADD CONSTRAINT fk_users_current_vote
        FOREIGN KEY (current_vote_id) REFERENCES votes (id);
