-- =========================================================
-- 가게별 1인 1댓글 / KST 일별 서울 랭킹 스냅샷
-- 모든 TIMESTAMP 값은 애플리케이션에서 UTC Instant 로 저장한다.
-- =========================================================

CREATE TABLE comments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT       NOT NULL,
    user_id       BIGINT       NOT NULL,
    content       VARCHAR(500) NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_comments_restaurant
        FOREIGN KEY (restaurant_id) REFERENCES restaurants (id),
    CONSTRAINT fk_comments_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ux_comments_restaurant_user
        UNIQUE (restaurant_id, user_id),
    CONSTRAINT ck_comments_content
        CHECK (length(btrim(content)) BETWEEN 1 AND 500)
);

CREATE INDEX idx_comments_restaurant_created
    ON comments (restaurant_id, created_at DESC, id DESC);

CREATE TABLE ranking_daily_snapshots (
    snapshot_date DATE      NOT NULL,
    restaurant_id BIGINT    NOT NULL,
    rank           INT       NOT NULL,
    vote_count     INT       NOT NULL,
    captured_at    TIMESTAMP NOT NULL,
    CONSTRAINT pk_ranking_daily_snapshots
        PRIMARY KEY (snapshot_date, restaurant_id),
    CONSTRAINT fk_ranking_daily_snapshots_restaurant
        FOREIGN KEY (restaurant_id) REFERENCES restaurants (id),
    CONSTRAINT ck_ranking_daily_snapshots_rank
        CHECK (rank > 0),
    CONSTRAINT ck_ranking_daily_snapshots_vote_count
        CHECK (vote_count >= 0)
);

CREATE INDEX idx_ranking_daily_snapshots_restaurant_date
    ON ranking_daily_snapshots (restaurant_id, snapshot_date DESC);
